# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

cities = [
  "Banovići",
  "Banja Luka",
  "Berkovići",
  "Bihać",
  "Bijeljina",
  "Bileća",
  "Bosanska Krupa",
  "Bosanski Petrovac",
  "Bosansko Grahovo",
  "Bratunac",
  "Brekovica",
  "Brčko",
  "Breza",
  "Bugojno",
  "Busovača",
  "Bužim",
  "Cazin",
  "Centar Sarajevo",
  "Čajniče",
  "Čapljina",
  "Čelinac",
  "Čitluk",
  "Derventa",
  "Doboj",
  "Doboj Istok",
  "Doboj Jug",
  "Domaljevac-Šamac",
  "Donji Vakuf",
  "Donji Žabar",
  "Drvar",
  "Fojnica",
  "Foča",
  "Foča-Ustikolina",
  "Gacko",
  "Glamoč",
  "Goražde",
  "Gornji Vakuf-Uskoplje",
  "Gračanica",
  "Gradiška",
  "Grude",
  "Hadžići",
  "Han Pijesak",
  "Ilidža",
  "Ilijaš",
  "Istočna Ilidža",
  "Istočni Mostar",
  "Istočni Stari Grad",
  "Istočno Novo Sarajevo",
  "Istočno Sarajevo",
  "Jablanica",
  "Jajce",
  "Jezero",
  "Kakanj",
  "Kalesija",
  "Kalinić",
  "Kalinovik",
  "Kiseljak",
  "Kladanj",
  "Ključ",
  "Kneževo",
  "Kotor Varoš",
  "Konjic",
  "Kreševo",
  "Kupres",
  "Kupres (RS)",
  "Laktaši",
  "Lopare",
  "Lukavac",
  "Ljubinje",
  "Livno",
  "Maglaj",
  "Milići",
  "Modriča",
  "Mostar",
  "Mrkonjić Grad",
  "Neum",
  "Nevesinje",
  "Novi Grad",
  "Novi Grad Sarajevo",
  "Novi Travnik",
  "Novo Goražde",
  "Novo Sarajevo",
  "Odžak",
  "Olovo",
  "Orašje",
  "Pale",
  "Pale-Prača",
  "Petrovac",
  "Petrovo",
  "Posušje",
  "Prijedor",
  "Prnjavor",
  "Prozor-Rama",
  "Ravno",
  "Ribnik",
  "Rogatica",
  "Rudo",
  "Sanski Most",
  "Sapna",
  "Sarajevo",
  "Srebrenica",
  "Srebrenik",
  "Stari Grad Sarajevo",
  "Stanari",
  "Stolac",
  "Šamac",
  "Šekovići",
  "Šipovo",
  "Široki Brijeg",
  "Sokolac",
  "Srbac",
  "Srebrenik",
  "Srebrenica",
  "Stari Grad Sarajevo",
  "Stanari",
  "Stolac",
  "Teslić",
  "Tešanj",
  "Tomislavgrad",
  "Travnik",
  "Trebinje",
  "Trnovo",
  "Tuzla",
  "Ugljevik",
  "Usora",
  "Ustiprača",
  "Vareš",
  "Velika Kladuša",
  "Vitez",
  "Višegrad",
  "Vlasenica",
  "Vogošća",
  "Vozuća",
  "Zavidovići",
  "Zenica",
  "Zvornik",
  "Žepče",
  "Živinice",
  "Šamac",
  "Šekovići",
  "Šipovo",
  "Široki Brijeg"
]

task_categories = [
  "Other",
  "Home Repairs",
  "Plumbing",
  "Electrical",
  "Mechanical",
  "Carpentry",
  "Painting",
  "Assembly",
  "Mounting",
  "Appliance Installation",
  "Cleaning",
  "Hauling",
  "Moving",
  "Yard Work",
  "Construction",
  "Demolition",
  "Decoration",
  "Errand Running",
  "Tech Setup"
]

skills = [
  "Home Repairs",
  "Plumbing",
  "Electrical",
  "Mechanical",
  "Carpentry",
  "Painting",
  "Assembly",
  "Mounting",
  "Appliance Installation",
  "Cleaning",
  "Hauling",
  "Moving",
  "Yard Work",
  "Construction",
  "Demolition",
  "Decoration",
  "Errand Running",
  "Tech Setup"
]

cities.each do |city|
  City.find_or_create_by!(name: city)
end

task_categories.each do |task_category|
  TaskCategory.find_or_create_by!(name: task_category)
end

skills.each do |skill|
  Skill.find_or_create_by!(name: skill)
end
